# Generated by Django 4.1.2 on 2022-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("louslist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="userID",
            field=models.CharField(max_length=200),
        ),
    ]
