# Generated by Django 4.1.1 on 2022-10-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
