# Generated by Django 4.1.1 on 2022-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0003_profile_relationship_remove_course_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
