# Generated by Django 4.1.2 on 2022-11-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0005_alter_course_days_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
