# Generated by Django 4.1.1 on 2022-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("id_num", models.IntegerField()),
                ("email", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(name="Thought",),
    ]
